### ISSUE TITLE
EPIC: Prepare automation & integration for new Rupture Set builds

### ISSUE THREAD

**Issue by chrisbc** [GNS-Science/nshm-nz-opensha#114]
Needed to support rupture set builds for sensivity tests:

Done when:
 - [x] saves Tasks, files and relationships with all metadata to the Toshi API  (depends on new API deployments test/prod)
 - [x] makes efficient use of cluster resources/scheduling. consider if Python MPI is required. 
 - [x] support Crustal Azimuthal ruptures and sensitivity options
 - [x] supports Subduction ruptures and sensitivity options
 - [x] support Crustal Coulomb  ruptures and sensitivity options

**Comment by chrisbc** [comment]
see subtask #121

**Comment by chrisbc** [comment]
- #134 sorted Azimuthal and Coulomb
 - TODO: Subduction
