### ISSUE TITLE
Set up scalable grand inversions

### ISSUE THREAD

**Issue by chrisbc** [GNS-Science/nshm-nz-opensha#128]
So we can run multiple inversion jobs concurrently on either single node or cluster platforms

NB As this is the 'big task , here' we'll be testing/using this mainly on cluster environment, but it should also support single nodes.

Done when:
 - [x] define num concurrent tasks 
 - [x] define threads per task
 - [ ] use Rupset inputs from API refs
 - [x] save outputs  to API
- [x] deploy and test on beavan cluster
- [x] update beavan scripts to use new JDK and gradle configs

**Comment by chrisbc** [comment]
Deferring automated input for now, we can work without it. 
#TODO - migrate to simplified GI schema on Toshi_api
